### ISSUE TITLE
JOSS: ELECTRIC review

### ISSUE THREAD

**Issue by govarguz** [WelbornGroup/ELECTRIC#19]
This is part of the review process for [openjournals/joss-reviews/issues/2576](https://github.com/openjournals/joss-reviews/issues/2576)

The Ms. describes the functionalities of ELECTRIC in a very succinct manner, which also shows the strong background of the Authors in the field. 
I recommend addressing the following points before publication.

1. In the last lines of the SUMMARY a phrase reads "_ELECTRIC enables splitting of the total field into contributions from different components of the system, by molecules or by residues as specified in a reference PDB file_". However, looking at the tests or examples @ELECTRIC_github, I was not able to see any example using a reference PDB file. In fact, since PDB is one of the most used formats in biomolecular simulations an example using this format would fit nicely to the description and the whole submission.

2. Within the summary, and as understood that ELECTRIC has a couple of dependencies,  I would suggest to include a flowchart diagram. This may facilitate also the awareness of ELECTRIC to any potential users.

Minor
3. I would also recommend to have a Jupyter Notebook example, powered e.g. by myBinder to show the clear capabilities of ELECTRIC.

JOSS related points, I want to remark and point-out on the Community guidelines and also an outlook of the project. In order to bring the attention of the community and perhaps join projects that may overlap, as we know the molecular simulation community grows fast.

**Comment by janash** [comment]
Hi @govarguz - I am working on these suggestions. Can you clarify what type of flowchart diagram you mean in point 2? Do you mean a flowchart diagram for the installation process?

**Comment by govarguz** [comment]
@janash, I meant more a generic flowchart which spots where is Electric within molecular simulation environments. For example it works within the Molssi driver Interface, and requires simulation trajectories, and so on. 
So that, one clearly identifies it as a post-processing/analysis tool within a simulation pipeline.
Does it answer your question?

**Comment by janash** [comment]
Yes, I think so. I will draft a flowchart and we can iterate if necessary.

**Comment by janash** [comment]
Hi @govarguz, I've attempted to address your points. Most of these seemed like they could be fixed through improved documentation, so please see the new GitHub pages for this software : https://welborngroup.github.io/ELECTRIC/

1. and 3. - The tutorial on the GitHub pages site gives a tutorial for running an analysis on a protein MD simulation using the `--byres` option - https://welborngroup.github.io/ELECTRIC/tutorial.html . We also felt that this was a good response to point 3. ELECTRIC is a python script, but runs the compiled Fortran program MDI-Tinker in the background. This seems too computationally expensive for a Binder session. ELECTRIC is also intended to be used as command line tool, in a script similar to what you would see on the Usage page (https://welborngroup.github.io/ELECTRIC/usage.html). We felt this step-by-step tutorial was a good alternative to a Jupyter notebook. 

2. We have added flowchart diagram on the Usage page (https://welborngroup.github.io/ELECTRIC/usage.html) in attempt to show where ELECTRIC fits in relative to running your MD simulation.

Other points of improvement - We have also greatly simplified the installation process, thanks to a suggestion from @amandadumi

**Comment by govarguz** [comment]
@janash 
I see. In my opinion ELECTRIC is ready for publication at JOSS
